Repository AcademySoftwareFoundation/OpenColorIO, pull requests merged in 2019-09, with the labels that each got.

#810 Adsk Contrib - Move tests out of source files.
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/Context.cpp
  src/OpenColorIO/fileformats/FileFormat3DL.cpp
  tests/cpu/CMakeLists.txt
  tests/cpu/Context_tests.cpp
  tests/cpu/UnitTest.cpp
  tests/cpu/UnitTest.h
  tests/cpu/UnitTestUtils.cpp
  tests/cpu/UnitTestUtils.h
  tests/cpu/fileformats/FileFormat3DL_tests.cpp
Labels: Major

#809 Adsk Contrib - Case for GPU source files
  tests/gpu/CMakeLists.txt
  tests/gpu/ExpOps_test.cpp
  tests/gpu/LogOps_test.cpp
Labels: Minor

#811 Adsk Contrib - Impose explicit namespaces
  src/OpenColorIO/MathUtils.cpp
  src/OpenColorIO/Op.cpp
  src/OpenColorIO/OpOptimizers.cpp
  src/OpenColorIO/SSE.cpp
  src/OpenColorIO/fileformats/FileFormatIridasCube.cpp
  src/OpenColorIO/fileformats/FileFormatIridasLook.cpp
  src/OpenColorIO/ops/CDL/CDLOps.cpp
  src/OpenColorIO/ops/Exponent/ExponentOps.cpp
  src/OpenColorIO/ops/Exponent/ExponentOps.h
  src/OpenColorIO/ops/Matrix/MatrixOpCPU.cpp
  src/OpenColorIO/ops/Matrix/MatrixOps.cpp
  src/OpenColorIO/ops/NoOp/NoOps.cpp
  src/OpenColorIO/ops/Range/RangeOps.cpp
  src/OpenColorIO/transforms/FixedFunctionTransform.cpp
  src/OpenColorIO/transforms/RangeTransform.cpp
  src/apps/ociolutimage/main.cpp
  tests/gpu/CDLOps_test.cpp
  tests/gpu/Config_test.cpp
  tests/gpu/ECOps_test.cpp
  tests/gpu/ExpOps_test.cpp
  tests/gpu/FixedFunctionOps_test.cpp
  tests/gpu/GPUHelpers.cpp
  tests/gpu/GPUUnitTest.cpp
  tests/gpu/LogOps_test.cpp
  tests/gpu/Lut1DOp_test.cpp
  tests/gpu/Lut3DOp_test.cpp
  tests/gpu/MatrixOps_test.cpp
  tests/gpu/RangeOps_test.cpp
Labels: Minor

#816 Adsk Contrib - Improve the Windows/Vc++ pdb support
  CMakeLists.txt
  src/OpenColorIO/CMakeLists.txt
Labels: Minor

#817 Adsk Contrib - Fix bugs and some warnings found by SonarCloud
  src/OpenColorIO/CPUProcessor.cpp
  src/OpenColorIO/DynamicProperty.h
  src/OpenColorIO/OpOptimizers.cpp
  src/OpenColorIO/fileformats/FileFormatDiscreet1DL.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.cpp
  src/OpenColorIO/fileformats/xmlutils/XMLReaderUtils.h
  src/OpenColorIO/ops/Gamma/GammaOpData.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpCPU.cpp
  src/OpenColorIO/ops/NoOp/NoOps.cpp
  src/apps/apputils/argparse.cpp
  src/apps/apputils/argparse.h
  tests/cpu/UnitTest.h
Labels: Minor

#812 Adsk Contrib - Refactor RangeTransform to improve the RangeOp creation
  include/OpenColorIO/OpenColorTransforms.h
  src/OpenColorIO/Transform.cpp
  src/OpenColorIO/ops/Range/RangeOps.cpp
  src/OpenColorIO/transforms/RangeTransform.cpp
Labels: Minor

#824 Adsk Contrib - Fix build breaks of the Linux static library compilation
  CMakeLists.txt
  share/cmake/projects/BuildPystring.cmake
  src/OpenColorIO/CMakeLists.txt
  src/bindings/python/CMakeLists.txt
  tests/gpu/CMakeLists.txt
Labels: Major

#833 Adsk Contrib - Remove a useless variable
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.cpp
Labels: Major

#834 Backport support for GLSL 4.0 to the v1.1 branch
  export/OpenColorIO/OpenColorTypes.h
  src/core/GpuShaderUtils.cpp
  src/core/ParseUtils.cpp
  src/core/Processor.cpp
  src/jniglue/org/OpenColorIO/GpuLanguage.java
  src/jniglue/tests/org/OpenColorIO/GlobalsTest.java
  src/jniglue/tests/org/OpenColorIO/GpuShaderDescTest.java
  src/pyglue/PyConstants.cpp
  src/pyglue/tests/ConstantsTest.py
  src/pyglue/tests/GpuShaderDescTest.py
Labels: v1.0

#825 Adsk Contrib - Remove legacy LUT structs.
  src/OpenColorIO/BitDepthUtils.cpp
  src/OpenColorIO/BitDepthUtils.h
  src/OpenColorIO/GPUProcessor.cpp
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/fileformats/FileFormat3DL.cpp
  src/OpenColorIO/fileformats/FileFormatCSP.cpp
  src/OpenColorIO/fileformats/FileFormatDiscreet1DL.cpp
  src/OpenColorIO/fileformats/FileFormatHDL.cpp
  src/OpenColorIO/fileformats/FileFormatICC.cpp
  src/OpenColorIO/fileformats/FileFormatIridasCube.cpp
  src/OpenColorIO/fileformats/FileFormatIridasItx.cpp
  src/OpenColorIO/fileformats/FileFormatIridasLook.cpp
  src/OpenColorIO/fileformats/FileFormatPandora.cpp
  src/OpenColorIO/fileformats/FileFormatResolveCube.cpp
  src/OpenColorIO/fileformats/FileFormatSpi1D.cpp
  src/OpenColorIO/fileformats/FileFormatSpi3D.cpp
  src/OpenColorIO/fileformats/FileFormatTruelight.cpp
  src/OpenColorIO/fileformats/FileFormatVF.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.h
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOp.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOp.h
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.h
  src/OpenColorIO/ops/Matrix/MatrixOps.cpp
  src/OpenColorIO/ops/Matrix/MatrixOps.h
  src/OpenColorIO/ops/NoOp/NoOps.cpp
  tests/cpu/fileformats/FileFormat3DL_tests.cpp
  tests/data/files/iridas_1d.cube
  tests/data/files/iridas_3d.cube
  tests/data/files/iridas_3d.itx
  tests/data/files/nuke_3d.vf
  tests/data/files/pandora_3d.m3d
  tests/data/files/resolve_1d3d.cube
  tests/gpu/Lut1DOp_test.cpp
Labels: Major

#838 Address two warnings in GCC 8/9
  src/core/Config.cpp
  src/core/Platform.cpp
  src/core/Platform.h
  src/pyglue/CMakeLists.txt
Labels: v1.0

#826 Adsk Contrib - CDL rework for description.
  include/OpenColorIO/OpenColorTransforms.h
  src/OpenColorIO/fileformats/FileFormatCC.cpp
  src/OpenColorIO/fileformats/FileFormatCCC.cpp
  src/OpenColorIO/fileformats/FileFormatCDL.cpp
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/fileformats/cdl/CDLParser.cpp
  src/OpenColorIO/fileformats/cdl/CDLParser.h
  src/OpenColorIO/fileformats/cdl/CDLReaderHelper.cpp
  src/OpenColorIO/fileformats/cdl/CDLReaderHelper.h
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.h
  src/OpenColorIO/fileformats/ctf/CTFTransform.cpp
  src/OpenColorIO/fileformats/xmlutils/XMLReaderHelper.cpp
  src/OpenColorIO/fileformats/xmlutils/XMLReaderHelper.h
  src/OpenColorIO/transforms/CDLTransform.cpp
  src/OpenColorIO/transforms/CDLTransform.h
  tests/data/files/cdl_test1.ccc
  tests/data/files/cdl_test1.cdl
  tests/python/OpenColorIOTestSuite.py
Labels: Major

#827 Adsk Contrib - Improve the performance of integer bit-depth processing
  include/OpenColorIO/OpenColorIO.h
  src/OpenColorIO/CPUProcessor.cpp
  src/OpenColorIO/CPUProcessor.h
  src/OpenColorIO/ImageDesc.cpp
  src/OpenColorIO/ImagePacking.cpp
  src/OpenColorIO/ImagePacking.h
  src/OpenColorIO/Op.cpp
  src/OpenColorIO/Op.h
  src/OpenColorIO/OpOptimizers.cpp
  src/OpenColorIO/ScanlineHelper.cpp
  src/OpenColorIO/ScanlineHelper.h
  src/apps/ocioperf/main.cpp
  src/utils/oiiohelpers/oiiohelpers.cpp
  src/utils/oiiohelpers/oiiohelpers.h
  tests/cpu/UnitTest.h
Labels: Major

#835 Adsk Contrib - Port a CDL Transform fix from master to OCIOv1
  src/core/CDLTransform.cpp
  src/core/Platform.cpp
  src/core/Platform.h
Labels: v1.0

#836 Adsk Contrib - Port a getenv() fix from master to OCIOv1
  src/core/Platform.cpp
Labels: v1.0

#829 Adsk Contrib - CTF write fixes
  src/OpenColorIO/Processor.cpp
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderUtils.cpp
  src/OpenColorIO/fileformats/ctf/CTFTransform.cpp
  src/OpenColorIO/transforms/FileTransform.cpp
  src/apps/ociowrite/main.cpp
  tests/cpu/CMakeLists.txt
  tests/cpu/Processor_tests.cpp
  tests/cpu/fileformats/FileFormatCTF_tests.cpp
  tests/cpu/fileformats/ctf/CTFTransform_tests.cpp
  tests/cpu/transforms/FileTransform_tests.cpp
Labels: Critical, v2.0
