Repository AcademySoftwareFoundation/OpenColorIO, pull requests merged in 2019-10, with the labels that each got.

#832 Replace AutoLock with std::lock_guard
  src/OpenColorIO/Mutex.h
Labels: Minor

#839 Adsk Contrib - Fix some missing symbol exports
  include/OpenColorIO/OpenColorIO.h
Labels: Minor

#845 Adsk Contrib - Add a missing comment
  src/OpenColorIO/CPUProcessor.h
Labels: Minor

#840 Port GCC 9 compiler fixes from RB-1.1 to master
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/Platform.cpp
  src/OpenColorIO/Platform.h
  src/OpenColorIO/fileformats/FileFormatDiscreet1DL.cpp
Labels: Minor

#847 Adsk Contrib - Ability to customize the default logging mechanism.
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/Logging.cpp
  src/OpenColorIO/fileformats/FileFormatCC.cpp
  src/OpenColorIO/fileformats/FileFormatCDL.cpp
  src/OpenColorIO/fileformats/xmlutils/XMLReaderHelper.cpp
  tests/cpu/CMakeLists.txt
  tests/cpu/Logging_tests.cpp
  tests/cpu/UnitTest.cpp
  tests/cpu/UnitTest.h
  tests/cpu/UnitTestUtils.cpp
  tests/cpu/UnitTestUtils.h
  tests/cpu/fileformats/FileFormatCTF_tests.cpp
  tests/data/files/transform_corrupted_tag.clf
  tests/gpu/GPUUnitTest.cpp
Labels: Minor

#848 Adsk Contrib - Add color space removal
  include/OpenColorIO/OpenColorIO.h
  src/OpenColorIO/Config.cpp
Labels: Minor

#849 Adsk Contrib - Add Raw configuration access
  include/OpenColorIO/OpenColorIO.h
  src/OpenColorIO/Config.cpp
  src/apps/ocioperf/CMakeLists.txt
  tests/python/MainTest.py
Labels: Minor

#860 Adsk Contrib - Improve RangeTransform
  src/OpenColorIO/ops/Range/RangeOpCPU.h
  src/OpenColorIO/ops/Range/RangeOpGPU.h
  src/OpenColorIO/ops/Range/RangeOps.cpp
  src/OpenColorIO/ops/Range/RangeOps.h
  src/OpenColorIO/transforms/RangeTransform.cpp
  src/OpenColorIO/transforms/RangeTransform.h
  tests/cpu/CMakeLists.txt
  tests/cpu/transforms/RangeTransform_tests.cpp
Labels: Minor, v2.0

#872 Bump OpenImageIO tag version to latest
  share/docker/dockerfile_centos7_gcc48
  share/docker/dockerfile_ubuntu16_gcc54
Labels: Minor

#876 Fix macOS CI python install script
  share/ci/scripts/macos/install_python.sh
Labels: Critical

#869 Adsk Contrib - Add 10 & 12 bit-depth support
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/CPUProcessor.cpp
  src/OpenColorIO/ImageDesc.cpp
Labels: Minor, v2.0

#873 Adsk Contrib - Various misc. changes
  CMakeLists.txt
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTransforms.h
  src/OpenColorIO/Platform.cpp
  src/OpenColorIO/fileformats/FileFormat3DL.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderUtils.cpp
  src/OpenColorIO/fileformats/ctf/CTFTransform.cpp
  src/OpenColorIO/fileformats/xmlutils/XMLWriterUtils.h
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOpData.cpp
  src/apps/ociobakelut/main.cpp
  src/apps/ociocheck/main.cpp
  src/apps/ociodisplay/main.cpp
  src/apps/ociolutimage/main.cpp
  src/apps/ocioperf/main.cpp
  src/apps/ociowrite/main.cpp
  vendor/CMakeLists.txt
Labels: Minor, v2.0

#874 Adsk Contrib - Remove useless warnings from make files.
  share/cmake/modules/FindExpat.cmake
  share/cmake/modules/FindIlmBase.cmake
  share/cmake/modules/FindLCMS2.cmake
  share/cmake/modules/FindPystring.cmake
  share/cmake/modules/FindYamlCpp.cmake
Labels: Minor, v2.0

#870 Adsk Contrib - Transforms interface
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTransforms.h
  src/OpenColorIO/CPUProcessor.cpp
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/fileformats/FileFormatCC.cpp
  src/OpenColorIO/fileformats/FileFormatCCC.cpp
  src/OpenColorIO/fileformats/FileFormatCDL.cpp
  src/OpenColorIO/fileformats/FileFormatCSP.cpp
  src/OpenColorIO/fileformats/FileFormatHDL.cpp
  src/OpenColorIO/fileformats/FileFormatResolveCube.cpp
  src/OpenColorIO/ops/CDL/CDLOps.cpp
  src/OpenColorIO/ops/Exponent/ExponentOps.cpp
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOps.cpp
  src/OpenColorIO/ops/Gamma/GammaOps.cpp
  src/OpenColorIO/ops/Log/LogOps.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOp.cpp
  src/OpenColorIO/ops/Matrix/MatrixOps.cpp
  src/OpenColorIO/ops/Range/RangeOps.cpp
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOps.cpp
  src/OpenColorIO/transforms/CDLTransform.cpp
  src/OpenColorIO/transforms/DisplayTransform.cpp
  src/OpenColorIO/transforms/ExponentTransform.cpp
  src/OpenColorIO/transforms/ExposureContrastTransform.cpp
  src/OpenColorIO/transforms/GroupTransform.cpp
  src/OpenColorIO/transforms/MatrixTransform.cpp
  src/apps/ociobakelut/main.cpp
  src/apps/ociodisplay/main.cpp
  src/bindings/python/DocStrings/GroupTransform.py
  src/bindings/python/PyConfig.cpp
  src/bindings/python/PyExponentTransform.cpp
  src/bindings/python/PyGroupTransform.cpp
  src/bindings/python/PyMatrixTransform.cpp
  src/bindings/python/PyUtil.cpp
  src/bindings/python/PyUtil.h
  tests/cpu/fileformats/FileFormat3DL_tests.cpp
  tests/cpu/fileformats/FileFormatCTF_tests.cpp
  tests/gpu/CDLOps_test.cpp
  tests/gpu/ECOps_test.cpp
  tests/gpu/ExpOps_test.cpp
  tests/gpu/MatrixOps_test.cpp
  tests/python/TransformsTest.py
Labels: Minor, v2.0
