Repository AcademySoftwareFoundation/OpenColorIO, pull requests merged in 2019-08, with the labels that each got.

#792 Adsk Contrib - Fix doc generation on Windows
  docs/CMakeLists.txt
  ext/CMakeLists.txt
  include/OpenColorIO/OpenColorIO.h
  share/cmake/macros/FindPythonPackage.cmake
  share/cmake/modules/FindSphinx.cmake
Labels: Documentation, Minor

#793 Adsk Contrib - Fix some warnings detected by SonarCloud
  src/OpenColorIO/Context.cpp
  src/OpenColorIO/UnitTest.cpp
  src/OpenColorIO/UnitTest.h
  src/OpenColorIO/fileformats/xmlutils/XMLReaderUtils.cpp
  src/OpenColorIO/fileformats/xmlutils/XMLReaderUtils.h
  src/OpenColorIO/ops/Exponent/ExponentOps.cpp
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOpCPU.cpp
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOps.cpp
  src/OpenColorIO/ops/Gamma/GammaOpCPU.cpp
  src/OpenColorIO/ops/Gamma/GammaOpData.cpp
  src/OpenColorIO/ops/Gamma/GammaOpData.h
  src/OpenColorIO/ops/Gamma/GammaOps.cpp
  src/OpenColorIO/ops/Log/LogOpCPU.cpp
  src/OpenColorIO/ops/Log/LogOps.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpCPU.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOp.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpCPU.cpp
  src/OpenColorIO/ops/Matrix/MatrixOpCPU.cpp
  src/OpenColorIO/ops/Matrix/MatrixOpData.h
  src/OpenColorIO/ops/Matrix/MatrixOps.cpp
  src/OpenColorIO/ops/NoOp/NoOps.cpp
  src/OpenColorIO/ops/NoOp/NoOps.h
  src/OpenColorIO/ops/Range/RangeOpData.h
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOpCPU.cpp
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOps.cpp
  tests/gpu/GPUUnitTest.cpp
  tests/gpu/GPUUnitTest.h
Labels: Minor

#801 Adsk Contrib - Adjust ParseNumber
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.cpp
  src/OpenColorIO/fileformats/xmlutils/XMLReaderHelper.h
  src/OpenColorIO/fileformats/xmlutils/XMLReaderUtils.cpp
  src/OpenColorIO/fileformats/xmlutils/XMLReaderUtils.h
Labels: Major, v2.0

#802 Fix Python example for full display pipeline
  docs/developers/usage_examples.rst
Labels: Documentation

#803 Adsk Contrib - Addressing TODO from SSE.h
  src/OpenColorIO/SSE.h
  src/OpenColorIO/ops/CDL/CDLOpCPU.cpp
Labels: Minor, v2.0

#805 Adsk Contrib - Disable the assert dialog box for debug VC++ CRT libraries
  src/OpenColorIO/UnitTest.cpp
  src/OpenColorIO/UnitTest.h
  src/OpenColorIO/transforms/FileTransform.cpp
  tests/data/files/rgb-cmy.jpg
Labels: Minor, v2.0

#806 2019-08-19 TSC meeting minutes
  docs/tsc/meetings/2019-08-19.md
Labels: Minor

#808 fix typos in doc
  docs/userguide/baking_luts.rst
Labels: Documentation

#807 Adsk Contrib - Fix build breaks on macOS
  src/utils/oglbuilder/glsl.cpp
  tests/gpu/CMakeLists.txt
  tests/gpu/GPUUnitTest.cpp
Labels: Minor
