Repository AcademySoftwareFoundation/OpenColorIO, pull requests merged in 2019-05, with the labels that each got.

#737 Adsk Contrib - Add extra information to ociodisplay & ocioconvert
  src/apps/ocioconvert/main.cpp
  src/apps/ociodisplay/main.cpp
Labels: Minor, v2.0

#744 Fix stray isnan in Lut3DOp test
  src/OpenColorIO/ops/Lut3D/Lut3DOp.cpp
Labels: Minor, v2.0

#739 Adsk Contrib - Fix some TruelightOp issues
  src/OpenColorIO/ops/Truelight/TruelightOp.cpp
Labels: Critical, v2.0

#743 Adsk Contrib - Add dynamic properties and exposure contrast.
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTransforms.h
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/DynamicProperty.cpp
  src/OpenColorIO/DynamicProperty.h
  src/OpenColorIO/GpuShader.cpp
  src/OpenColorIO/GpuShader.h
  src/OpenColorIO/GpuShaderUtils.cpp
  src/OpenColorIO/GpuShaderUtils.h
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/Op.cpp
  src/OpenColorIO/Op.h
  src/OpenColorIO/OpBuilders.h
  src/OpenColorIO/ParseUtils.cpp
  src/OpenColorIO/Processor.cpp
  src/OpenColorIO/Processor.h
  src/OpenColorIO/Transform.cpp
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.h
  src/OpenColorIO/fileformats/ctf/CTFReaderUtils.h
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOpCPU.cpp
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOpCPU.h
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOpData.cpp
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOpData.h
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOpGPU.cpp
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOpGPU.h
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOps.cpp
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOps.h
  src/OpenColorIO/transforms/ExposureContrastTransform.cpp
  src/apps/ocioconvert/main.cpp
  src/apps/ociodisplay/main.cpp
  src/utils/oglbuilder/glsl.cpp
  src/utils/oglbuilder/glsl.h
  tests/cpu/CMakeLists.txt
  tests/data/files/exposure_contrast_bad_style.ctf
  tests/data/files/exposure_contrast_linear.ctf
  tests/data/files/exposure_contrast_log.ctf
  tests/data/files/exposure_contrast_missing_param.ctf
  tests/data/files/exposure_contrast_no_gamma.ctf
  tests/data/files/exposure_contrast_video.ctf
  tests/data/files/exposure_contrast_video_dp.ctf
  tests/data/files/multiple_ops.clf
  tests/gpu/CMakeLists.txt
  tests/gpu/ECOps_test.cpp
  tests/gpu/GPUUnitTest.cpp
  tests/gpu/GPUUnitTest.h
  tests/python/GpuShaderDescTest.py
Labels: Major, v2.0

#748 Adsk Contrib - Create an OpRcPtrVec managing the op bit-depths
  src/OpenColorIO/Op.cpp
  src/OpenColorIO/Op.h
  src/OpenColorIO/OpOptimizers.cpp
  src/OpenColorIO/Processor.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.cpp
  src/OpenColorIO/ops/NoOp/NoOps.cpp
  src/OpenColorIO/ops/NoOp/NoOps.h
  src/OpenColorIO/ops/Truelight/TruelightOp.cpp
  src/OpenColorIO/ops/reference/ReferenceOpData.cpp
  src/OpenColorIO/ops/reference/ReferenceOpData.h
  src/OpenColorIO/transforms/DisplayTransform.cpp
  src/OpenColorIO/transforms/LookTransform.cpp
  tests/data/files/reference_one_matrix.ctf
Labels: Minor, v2.0

#750 Adsk Contrib - Add missing ctf parsing.
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/Op.cpp
  src/OpenColorIO/Op.h
  src/OpenColorIO/UnitTestUtils.cpp
  src/OpenColorIO/UnitTestUtils.h
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.h
  src/OpenColorIO/fileformats/ctf/CTFReaderUtils.h
  src/OpenColorIO/fileformats/ctf/CTFTransform.h
  src/OpenColorIO/ops/CDL/CDLOps.cpp
  src/OpenColorIO/ops/CDL/CDLOps.h
  src/OpenColorIO/ops/Exponent/ExponentOps.cpp
  src/OpenColorIO/ops/Exponent/ExponentOps.h
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOpData.cpp
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOpData.h
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOps.cpp
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOps.h
  src/OpenColorIO/ops/Gamma/GammaOpData.cpp
  src/OpenColorIO/ops/Gamma/GammaOpData.h
  src/OpenColorIO/ops/Gamma/GammaOps.cpp
  src/OpenColorIO/ops/Gamma/GammaOps.h
  src/OpenColorIO/ops/Log/LogOpData.h
  src/OpenColorIO/ops/Log/LogOps.cpp
  src/OpenColorIO/ops/Log/LogOps.h
  src/OpenColorIO/ops/Range/RangeOps.cpp
  src/OpenColorIO/ops/Range/RangeOps.h
  src/OpenColorIO/transforms/FileTransform.cpp
  src/OpenColorIO/transforms/FixedFunctionTransform.cpp
  tests/data/files/ff_aces_redmod.ctf
  tests/data/files/ff_aces_surround.ctf
  tests/data/files/ff_surround.ctf
  tests/data/files/gamma_alpha_test1.ctf
  tests/data/files/gamma_alpha_test2.ctf
  tests/data/files/gamma_alpha_test3.ctf
  tests/data/files/gamma_alpha_test4.ctf
  tests/data/files/gamma_alpha_test5.ctf
  tests/data/files/gamma_alpha_test6.ctf
  tests/data/files/gamma_test1.ctf
  tests/data/files/gamma_test2.ctf
  tests/data/files/gamma_test3.ctf
  tests/data/files/gamma_test4.ctf
  tests/data/files/gamma_test5.ctf
  tests/data/files/gamma_test6.ctf
  tests/data/files/gamma_wrong_power.ctf
  tests/data/files/log_antilog10.ctf
  tests/data/files/log_antilog2.ctf
  tests/data/files/log_invalidstyle.ctf
  tests/data/files/log_lintolog_3chan.ctf
  tests/data/files/log_log10.ctf
  tests/data/files/log_log10_faulty_version.ctf
  tests/data/files/log_log2.ctf
  tests/data/files/log_logtolin.ctf
  tests/data/files/process_list_higher_version.ctf
Labels: Major, v2.0
