Repository AcademySoftwareFoundation/OpenColorIO, pull requests merged in 2019-04, with the labels that each got.

#715 Adsk Contrib - Improve Apps error reporting
  src/apps/ocioconvert/main.cpp
  src/apps/ociodisplay/main.cpp
  src/apps/ociolutimage/main.cpp
Labels: Minor, v2.0

#714 Adsk Contrib - Add CTF as a recognized extension.
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/transforms/FileTransform.cpp
  tests/python/TransformsTest.py
Labels: Minor, v2.0

#699 Adsk Contrib - Add the infrastructure for the Pixel Format support
  ext/oiio/src/include/unittest.h
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/BitDepthUtils.cpp
  src/OpenColorIO/BitDepthUtils.h
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/CPUProcessor.cpp
  src/OpenColorIO/CPUProcessor.h
  src/OpenColorIO/Op.h
  src/OpenColorIO/OpTools.cpp
  src/OpenColorIO/Processor.cpp
  src/OpenColorIO/Processor.h
  src/OpenColorIO/UnitTestUtils.h
  src/OpenColorIO/fileformats/FileFormatICC.cpp
  src/OpenColorIO/ops/CDL/CDLOpCPU.cpp
  src/OpenColorIO/ops/CDL/CDLOpCPU.h
  src/OpenColorIO/ops/CDL/CDLOps.cpp
  src/OpenColorIO/ops/Exponent/ExponentOps.cpp
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOpCPU.cpp
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOps.cpp
  src/OpenColorIO/ops/Gamma/GammaOpCPU.cpp
  src/OpenColorIO/ops/Gamma/GammaOps.cpp
  src/OpenColorIO/ops/Log/LogOpCPU.cpp
  src/OpenColorIO/ops/Log/LogOps.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpCPU.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOp.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpCPU.cpp
  src/OpenColorIO/ops/Matrix/MatrixOpCPU.cpp
  src/OpenColorIO/ops/Matrix/MatrixOpCPU.h
  src/OpenColorIO/ops/Matrix/MatrixOps.cpp
  src/OpenColorIO/ops/NoOp/NoOps.cpp
  src/OpenColorIO/ops/Range/RangeOpCPU.cpp
  src/OpenColorIO/ops/Range/RangeOps.cpp
  tests/cpu/CMakeLists.txt
Labels: Critical, v2.0

#712 Adsk Contrib - Add Reference OpData
  ext/oiio/src/include/unittest.h
  include/OpenColorIO/OpenColorIO.h
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/Context.cpp
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/Op.h
  src/OpenColorIO/OpBuilders.h
  src/OpenColorIO/Transform.cpp
  src/OpenColorIO/UnitTestUtils.cpp
  src/OpenColorIO/UnitTestUtils.h
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/fileformats/FileFormatICC.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.h
  src/OpenColorIO/fileformats/ctf/CTFReaderUtils.h
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.cpp
  src/OpenColorIO/ops/NoOp/NoOps.cpp
  src/OpenColorIO/ops/NoOp/NoOps.h
  src/OpenColorIO/ops/reference/ReferenceOpData.cpp
  src/OpenColorIO/ops/reference/ReferenceOpData.h
  src/OpenColorIO/transforms/FileTransform.cpp
  src/OpenColorIO/transforms/FileTransform.h
  src/bindings/python/DocStrings/Config.py
  src/bindings/python/DocStrings/Context.py
  src/bindings/python/PyConfig.cpp
  src/bindings/python/PyContext.cpp
  tests/cpu/CMakeLists.txt
  tests/data/files/reference_alias.ctf
  tests/data/files/reference_alias_path.ctf
  tests/data/files/reference_cycle_2levels.ctf
  tests/data/files/reference_cycle_2levels_2.ctf
  tests/data/files/reference_cycle_3levels.ctf
  tests/data/files/reference_cycle_3levels_2.ctf
  tests/data/files/reference_cycle_3levels_3.ctf
  tests/data/files/reference_cycle_itself.ctf
  tests/data/files/reference_cycle_path_not_equal.ctf
  tests/data/files/reference_nested.ctf
  tests/data/files/reference_nested_2.ctf
  tests/data/files/reference_path_missing_file.ctf
  tests/data/files/reference_utf8.ctf
  tests/data/files/references_same_twice.ctf
  tests/data/files/references_some_inverted.ctf
  tests/python/ConfigTest.py
  tests/python/ContextTest.py
Labels: Major, v2.0

#713 Adsk Contrib - LUT tests
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpGPU.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOp.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.cpp
  src/OpenColorIO/transforms/FileTransform.cpp
  tests/data/files/ABNorm_CxxxLog10toRec709_Full.xml
  tests/data/files/houdini.lut
  tests/data/files/lut1d_1024_hue_adjust_test.ctf
  tests/data/files/lut1d_comp.clf
  tests/data/files/lut1d_green.ctf
  tests/data/files/lut1d_hd_hueAdjust.ctf
  tests/data/files/lut1d_inverse_gpu_err.ctf
  tests/data/files/lut1d_inverse_halfdom_slog_fclut.ctf
  tests/data/files/lut1d_inverse_hd_hueAdjust.ctf
  tests/data/files/lut3d_17x17x17_10i_12i.clf
  tests/data/files/lut3d_2x2x2_32f_32f.clf
  tests/data/files/lut3d_bizarre.clf
  tests/data/files/not_a_ctf.xml
  tests/data/files/sRGB.lut
  tests/gpu/Lut1DOp_test.cpp
Labels: Major, v2.0

#727 Fix minor typos
  src/OpenColorIO/Baker.cpp
  src/OpenColorIO/Op.h
Labels: Minor

#722 Adsk Contrib - Add native bit depth support to the 1D LUT Op
  src/OpenColorIO/BitDepthUtils.h
  src/OpenColorIO/CPUProcessor.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpCPU.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpCPU.h
Labels: Major, v2.0

#723 Adsk Contrib - Enable 'warnings as error' for the Linux CI builds
  CMakeLists.txt
  src/OpenColorIO/OpTools.h
  src/OpenColorIO/PathUtils.cpp
  src/OpenColorIO/Processor.cpp
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.cpp
  src/OpenColorIO/ops/Log/LogOpData.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpCPU.cpp
  src/OpenColorIO/ops/Matrix/MatrixOps.cpp
  src/OpenColorIO/ops/Range/RangeOpGPU.cpp
  src/OpenColorIO/ops/Truelight/TruelightOp.cpp
  src/OpenColorIO/transforms/CDLTransform.cpp
  src/OpenColorIO/transforms/FixedFunctionTransform.cpp
  src/apps/ocioconvert/main.cpp
  tests/gpu/GPUUnitTest.cpp
Labels: Minor, v2.0

#732 Fix typo in FormatRegistry::getFormatNameByIndex
  src/OpenColorIO/transforms/FileTransform.cpp
Labels: Major, v1.0, v2.0

#724 Adsk Contrib - Improve the Matrix value precision in config file
  include/OpenColorIO/OpenColorTransforms.h
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/MathUtils.cpp
  src/OpenColorIO/MathUtils.h
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/SSE.cpp
  src/OpenColorIO/fileformats/FileFormatCSP.cpp
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/fileformats/xmlutils/XMLReaderUtils.cpp
  src/OpenColorIO/ops/CDL/CDLOpCPU.cpp
  src/OpenColorIO/ops/Exponent/ExponentOps.cpp
  src/OpenColorIO/ops/Log/LogOpCPU.cpp
  src/OpenColorIO/ops/Log/LogOpData.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpCPU.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOp.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpCPU.cpp
  src/OpenColorIO/ops/Matrix/MatrixOpData.h
  src/OpenColorIO/ops/Range/RangeOpCPU.cpp
  src/OpenColorIO/ops/Range/RangeOpData.cpp
  src/OpenColorIO/transforms/CDLTransform.cpp
  src/OpenColorIO/transforms/MatrixTransform.cpp
  tests/gpu/GPUUnitTest.cpp
Labels: Major, v2.0

#730 Adsk Contrib - Fix install issues around the OpenGLBuilder utility
  include/OpenColorIO/CMakeLists.txt
  src/apps/ociobakelut/CMakeLists.txt
  src/apps/ociocheck/CMakeLists.txt
  src/apps/ocioconvert/CMakeLists.txt
  src/apps/ocioconvert/main.cpp
  src/apps/ociodisplay/CMakeLists.txt
  src/apps/ociodisplay/main.cpp
  src/apps/ociolutimage/CMakeLists.txt
  src/bindings/python/CMakeLists.txt
  src/utils/CMakeLists.txt
  src/utils/oglbuilder/CMakeLists.txt
  src/utils/oglbuilder/glsl.cpp
  src/utils/oglbuilder/glsl.h
  src/utils/openglbuilder/CMakeLists.txt
  tests/gpu/CMakeLists.txt
  tests/gpu/GPUUnitTest.cpp
Labels: Major, v2.0

#733 Adsk Contrib - Fix some Mac GPU unit tests
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.h
  tests/gpu/CDLOps_test.cpp
  tests/gpu/FixedFunctionOps_test.cpp
  tests/gpu/LogOps_Test.cpp
  tests/gpu/Lut1DOp_test.cpp
  tests/gpu/Lut3DOp_test.cpp
  tests/gpu/RangeOps_test.cpp
Labels: Major, v2.0

#736 Fix typo in FormatRegistry::getFormatNameByIndex (RB-1.1)
  src/core/FileTransform.cpp
Labels: v1.0

#731 Adsk Contrib - Fix CTF Reference "inverted" parsing issue and edit a test file to validate.
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.cpp
  tests/data/files/references_some_inverted.ctf
Labels: Major, v2.0
