Repository AcademySoftwareFoundation/OpenColorIO, pull requests merged in 2019-03, with the labels that each got.

#677 Add USE_SSE Checks To Fix Compile on Linux
  src/core/Lut1DOp.cpp
  src/core/MathUtils.cpp
Labels: v1.0

#687 Adsk Contrib - Update Windows documentation
  docs/installation.rst
Labels: Minor, v2.0

#639 Adsk Contrib - Add the Gamma Op as defined by the Adsk CTF specification
  ext/oiio/src/include/unittest.h
  include/OpenColorIO/OpenColorTransforms.h
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/GpuShaderUtils.cpp
  src/OpenColorIO/GpuShaderUtils.h
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/Op.h
  src/OpenColorIO/OpBuilders.h
  src/OpenColorIO/OpOptimizers.cpp
  src/OpenColorIO/ParseUtils.cpp
  src/OpenColorIO/Transform.cpp
  src/OpenColorIO/fileformats/FileFormatICC.cpp
  src/OpenColorIO/ops/CDL/CDLOpData.cpp
  src/OpenColorIO/ops/CDL/CDLOpData.h
  src/OpenColorIO/ops/Exponent/ExponentOps.cpp
  src/OpenColorIO/ops/Exponent/ExponentOps.h
  src/OpenColorIO/ops/Gamma/GammaOpCPU.cpp
  src/OpenColorIO/ops/Gamma/GammaOpCPU.h
  src/OpenColorIO/ops/Gamma/GammaOpData.cpp
  src/OpenColorIO/ops/Gamma/GammaOpData.h
  src/OpenColorIO/ops/Gamma/GammaOpUtils.cpp
  src/OpenColorIO/ops/Gamma/GammaOpUtils.h
  src/OpenColorIO/ops/Gamma/GammaOps.cpp
  src/OpenColorIO/ops/Gamma/GammaOps.h
  src/OpenColorIO/ops/Range/RangeOps.cpp
  src/OpenColorIO/transforms/CDLTransform.cpp
  src/OpenColorIO/transforms/ExponentTransform.cpp
  src/OpenColorIO/transforms/ExponentWithLinearTransform.cpp
  tests/cpu/CMakeLists.txt
  tests/gpu/CMakeLists.txt
  tests/gpu/ExpOps_Test.cpp
  tests/python/ConfigTest.py
Labels: Major, v2.0

#681 Adsk Contrib - Improve error messages for the config file parsing.
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/transforms/CDLTransform.cpp
  src/OpenColorIO/transforms/MatrixTransform.cpp
  src/OpenColorIO/transforms/RangeTransform.cpp
Labels: Minor, v2.0

#684 Adsk Contrib - Remove unused functions
  src/OpenColorIO/MathUtils.cpp
Labels: Minor, v2.0

#685 Adsk Contrib - Restore Context.cpp tests by restoring a define.
  src/OpenColorIO/Context.cpp
  tests/cpu/CMakeLists.txt
Labels: Minor, v2.0

#692 Adsk Contrib - Use Lut1DOpData for for Discreet 1DL file format.
  src/OpenColorIO/fileformats/FileFormatDiscreet1DL.cpp
Labels: Minor, v2.0

#680 Adsk Contrib - Add the FixedFunctionOp support
  include/OpenColorIO/OpenColorTransforms.h
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/Op.h
  src/OpenColorIO/OpBuilders.h
  src/OpenColorIO/ParseUtils.cpp
  src/OpenColorIO/Transform.cpp
  src/OpenColorIO/ops/CDL/CDLOpData.cpp
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOpCPU.cpp
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOpCPU.h
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOpData.cpp
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOpData.h
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOpGPU.cpp
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOpGPU.h
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOps.cpp
  src/OpenColorIO/ops/FixedFunction/FixedFunctionOps.h
  src/OpenColorIO/transforms/FixedFunctionTransform.cpp
  tests/cpu/CMakeLists.txt
  tests/gpu/CMakeLists.txt
  tests/gpu/FixedFunctionOps_test.cpp
  tests/gpu/GPUUnitTest.cpp
  tests/gpu/GPUUnitTest.h
Labels: Major, v2.0

#693 Adsk Contrib - Fix the doc generation on Windows
  .appveyor.yml
  docs/CMakeLists.txt
Labels: Minor, v2.0

#694 Adsk Contrib - Fix a limitation for the 1D LUT inverse
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.h
Labels: Minor, v2.0

#698 ASWF mail list updates for RB-1.1
  README.md
  docs/CompatibleSoftware.rst
  docs/conf.py.in
  docs/configurations/index.rst
  docs/index.rst
Labels: v1.0

#678 Cherry picked fixes for proposed 1.1.x release
  src/apps/ocioconvert/main.cpp
  src/apps/ociodisplay/main.cpp
  src/apps/ociolutimage/main.cpp
  src/core/Config.cpp
  src/core/Display.cpp
  src/core/Platform.cpp
Labels: v1.0

#710 Adsk Contrib - Fix 'Not SSE' Linux build break for gcc 7.3
  src/OpenColorIO/ops/Gamma/GammaOpCPU.cpp
Labels: Critical, v2.0

#700 Adsk Contrib - Various adjustments to the Windows DLL
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/Platform.h
  src/OpenColorIO/res/version.rc.in
Labels: Minor, v2.0

#702 Adsk Contrib - Improve the compilation options
  CMakeLists.txt
  src/OpenColorIO/CMakeLists.txt
Labels: Minor, v2.0

#707 Adsk Contrib - Fix GPU tests build
  tests/gpu/GPUUnitTest.cpp
  tests/gpu/Lut1DOp_test.cpp
Labels: Critical, v2.0

#705 Update OCIO_VERSION_PATCH and ChangeLog for release 1.1.1
  CMakeLists.txt
  ChangeLog
Labels: v1.0

#703 Adsk Contrib: Add a file to control eol of test files.
  .gitattributes
Labels: Minor, v2.0

#706 Adsk contrib - Fix a bit depth issue for the Range Op
  src/OpenColorIO/ops/CDL/CDLOpData.cpp
  src/OpenColorIO/ops/CDL/CDLOpData.h
  src/OpenColorIO/ops/CDL/CDLOps.cpp
  src/OpenColorIO/ops/Gamma/GammaOpData.cpp
  src/OpenColorIO/ops/Gamma/GammaOpData.h
  src/OpenColorIO/ops/Gamma/GammaOps.cpp
  src/OpenColorIO/ops/Range/RangeOpData.cpp
  src/OpenColorIO/ops/Range/RangeOpData.h
  src/OpenColorIO/ops/Range/RangeOps.cpp
Labels: Minor, v2.0
