Repository AcademySoftwareFoundation/OpenColorIO, pull requests merged in 2019-12, with the labels that each got.

#895 Adsk Contrib - Fix more SonarCloud bugs
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderUtils.cpp
  src/OpenColorIO/fileformats/xmlutils/XMLWriterUtils.h
Labels: Minor, v2.0

#900 Fix various typos
  docs/FAQ.rst
  docs/developers/documentation_guidelines.rst
  docs/developers/getting_started.rst
  docs/installation.rst
  docs/introduction.rst
  docs/userguide/config_syntax.rst
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTransforms.h
  share/cmake/modules/FindExpat.cmake
  share/cmake/modules/FindLCMS2.cmake
  share/cmake/modules/FindYamlCpp.cmake
  share/cmake/modules/src/TestForDDImageVersion.cxx
  share/sphinx/ExtractRstFromSourceCPP.py
  src/OpenColorIO/Display.cpp
  src/OpenColorIO/MathUtils.cpp
  src/OpenColorIO/MathUtils.h
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/OpOptimizers.cpp
  src/OpenColorIO/SSE.h
  src/OpenColorIO/fileformats/FileFormat3DL.cpp
  src/OpenColorIO/fileformats/FileFormatCSP.cpp
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/fileformats/FileFormatDiscreet1DL.cpp
  src/OpenColorIO/fileformats/FileFormatHDL.cpp
  src/OpenColorIO/fileformats/FileFormatIridasLook.cpp
  src/OpenColorIO/fileformats/FileFormatResolveCube.cpp
  src/OpenColorIO/fileformats/cdl/CDLParser.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.cpp
  src/OpenColorIO/ops/cdl/CDLOpCPU.cpp
  src/OpenColorIO/ops/cdl/CDLOpData.h
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOpCPU.cpp
  src/OpenColorIO/ops/lut3d/Lut3DOpData.cpp
  src/OpenColorIO/ops/matrix/MatrixOpData.cpp
  src/OpenColorIO/ops/noop/NoOps.h
  src/OpenColorIO/ops/range/RangeOpData.cpp
  src/apps/apputils/argparse.cpp
  src/apps/ocioconvert/main.cpp
  src/bindings/python/DocStrings/Config.py
  src/bindings/python/PyUtil.cpp
  tests/cpu/Config_tests.cpp
  tests/cpu/DynamicProperty_tests.cpp
  tests/cpu/MathUtils_tests.cpp
  tests/cpu/fileformats/FileFormatCTF_tests.cpp
  tests/cpu/fileformats/xmlutils/XMLReaderUtils_tests.cpp
  tests/cpu/ops/log/LogOpCPU_tests.cpp
  tests/cpu/ops/lut1d/Lut1DOpData_tests.cpp
  tests/cpu/ops/lut3d/Lut3DOp_tests.cpp
  tests/gpu/GPUUnitTest.cpp
  tests/gpu/GPUUnitTest.h
  tests/gpu/Lut3DOp_test.cpp
Labels: Documentation

#896 Adsk Contrib - Add more FixedFunction algorithms
  CMakeLists.txt
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/ImageDesc.cpp
  src/OpenColorIO/Op.cpp
  src/OpenColorIO/OpOptimizers.cpp
  src/OpenColorIO/ParseUtils.cpp
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/fileformats/FileFormatDiscreet1DL.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderHelper.h
  src/OpenColorIO/fileformats/ctf/CTFReaderUtils.cpp
  src/OpenColorIO/fileformats/ctf/CTFReaderUtils.h
  src/OpenColorIO/fileformats/ctf/CTFTransform.cpp
  src/OpenColorIO/ops/fixedfunction/FixedFunctionOp.cpp
  src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
  src/OpenColorIO/ops/fixedfunction/FixedFunctionOpData.cpp
  src/OpenColorIO/ops/fixedfunction/FixedFunctionOpData.h
  src/OpenColorIO/ops/fixedfunction/FixedFunctionOpGPU.cpp
  tests/cpu/CMakeLists.txt
  tests/cpu/Config_tests.cpp
  tests/cpu/UnitTest.h
  tests/cpu/fileformats/FileFormatCTF_tests.cpp
  tests/cpu/ops/fixedfunction/FixedFunctionOpCPU_tests.cpp
  tests/cpu/ops/fixedfunction/FixedFunctionOp_tests.cpp
  tests/cpu/ops/lut1d/Lut1DOpCPU_tests.cpp
  tests/cpu/transforms/FileTransform_tests.cpp
  tests/cpu/transforms/FixedFunctionTransform_tests.cpp
  tests/data/files/deprecated_ops.ctf
  tests/data/files/ff_aces_redmod.ctf
  tests/data/files/ff_aces_surround.ctf
  tests/data/files/fixed_function.ctf
  tests/gpu/FixedFunctionOp_test.cpp
Labels: Major, v2.0

#899 Adsk Contrib - Add inactive color spaces
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/OCIOYaml.h
  tests/cpu/Config_tests.cpp
  tests/python/ConfigTest.py
Labels: Major, v2.0

#902 Adsk Contrib - Add some missing 'export' keyword in the public API
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTransforms.h
Labels: Minor, v2.0

#903 Adsk Contrib - remove namespace tabulation
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTransforms.h
  include/OpenColorIO/OpenColorTypes.h
Labels: Major, v2.0
