Repository AcademySoftwareFoundation/OpenColorIO, pull requests merged in 2019-01, with the labels that each got.

#644 Adsk Contrib - Fix a small doc issue
  include/OpenColorIO/OpenColorIO.h
Labels: Documentation, Minor, v2.0

#645 Adsk Contrib - Fix a compilation warning
  src/utils/openglbuilder/glsl.cpp
Labels: Minor, v2.0

#640 Adsk Contrib - Lut1D improvements (WIP)
  ext/CMakeLists.txt
  ext/ilmbasehalf-2.2.1.patch
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/MathUtils.cpp
  src/OpenColorIO/MathUtils.h
  src/OpenColorIO/OpTools.cpp
  src/OpenColorIO/OpTools.h
  src/OpenColorIO/fileformats/FileFormat3DL.cpp
  src/OpenColorIO/fileformats/FileFormatCSP.cpp
  src/OpenColorIO/fileformats/FileFormatDiscreet1DL.cpp
  src/OpenColorIO/fileformats/FileFormatHDL.cpp
  src/OpenColorIO/fileformats/FileFormatICC.cpp
  src/OpenColorIO/fileformats/FileFormatIridasCube.cpp
  src/OpenColorIO/fileformats/FileFormatIridasItx.cpp
  src/OpenColorIO/fileformats/FileFormatIridasLook.cpp
  src/OpenColorIO/fileformats/FileFormatPandora.cpp
  src/OpenColorIO/fileformats/FileFormatResolveCube.cpp
  src/OpenColorIO/fileformats/FileFormatSpi1D.cpp
  src/OpenColorIO/fileformats/FileFormatSpi3D.cpp
  src/OpenColorIO/fileformats/FileFormatTruelight.cpp
  src/OpenColorIO/fileformats/FileFormatVF.cpp
  src/OpenColorIO/fileformats/cdl/CDLParser.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.h
  src/OpenColorIO/ops/Lut1D/Lut1DOpCPU.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpCPU.h
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.h
  src/OpenColorIO/ops/Lut1D/Lut1DOpGPU.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpGPU.h
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.cpp
  src/OpenColorIO/ops/NoOp/NoOps.cpp
  src/OpenColorIO/ops/OpArray.h
  src/OpenColorIO/ops/Range/RangeOps.cpp
  tests/cpu/CMakeLists.txt
  tests/gpu/Lut1DOp_test.cpp
Labels: Major, v2.0

#642 Adsk Contrib - 3D LUT misc. changes
  src/OpenColorIO/GpuShader.cpp
  src/OpenColorIO/GpuShader.h
Labels: Minor, v2.0

#638 Fix wrong display returned by getDefaultDisplay()
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/Display.cpp
  src/OpenColorIO/Platform.cpp
Labels: Major, v2.0

#653 Adsk Contrib - LUT 3D compose function
  src/OpenColorIO/ops/Lut3D/Lut3DOpCPU.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.h
Labels: Minor, v2.0

#649 Adsk Contrib - Enable Windows CI build without SSE support
  .appveyor.yml
  src/OpenColorIO/ops/Matrix/MatrixOps.cpp
Labels: Minor, v2.0

#650 Adsk Contrib - Fix some Windows & Linux compilation warnings
  CMakeLists.txt
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/fileformats/FileFormatSpi3D.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.h
  src/apps/ociobakelut/CMakeLists.txt
  src/apps/ociocheck/CMakeLists.txt
  src/apps/ocioconvert/CMakeLists.txt
  src/apps/ociodisplay/CMakeLists.txt
  src/apps/ociolutimage/CMakeLists.txt
  src/bindings/python/CMakeLists.txt
  src/utils/openglbuilder/CMakeLists.txt
  src/utils/pystring/CMakeLists.txt
  tests/cpu/CMakeLists.txt
  tests/gpu/CMakeLists.txt
Labels: Minor, v2.0

#655 Adsk Contrib - Remove the cmake HOMEPAGE_URL
  CMakeLists.txt
Labels: Minor, v2.0

#652 Adsk Contrib - Optimization of the 3D LUT finalize
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/Processor.cpp
  src/OpenColorIO/Processor.h
  src/OpenColorIO/ops/Lut3D/Lut3DOp.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpGPU.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpGPU.h
  tests/cpu/CMakeLists.txt
Labels: Minor, v2.0

#651 Adsk Contrib - Lut3D inversion tests slow in debug on windows
  tests/gpu/Lut3DOp_test.cpp
Labels: Minor, v2.0
