Repository AcademySoftwareFoundation/OpenColorIO, pull requests merged in 2019-02, with the labels that each got.

#648 Adsk Contrib - Add Category support to Color Spaces
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/ColorSpace.cpp
  src/OpenColorIO/ColorSpaceSet.cpp
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/PrivateTypes.h
  tests/cpu/CMakeLists.txt
Labels: Critical, v2.0

#662 Adsk Contrib - Fix some gcc/clang warnings
  CMakeLists.txt
  src/OpenColorIO/ColorSpace.cpp
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/GpuShader.h
  src/OpenColorIO/fileformats/FileFormatIridasLook.cpp
  src/OpenColorIO/fileformats/cdl/CDLReaderHelper.cpp
  src/OpenColorIO/fileformats/cdl/CDLReaderHelper.h
  src/OpenColorIO/ops/CDL/CDLOps.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.h
  src/OpenColorIO/ops/Lut3D/Lut3DOp.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.h
  src/OpenColorIO/ops/Matrix/MatrixOpData.h
  src/OpenColorIO/ops/Range/RangeOpCPU.cpp
Labels: Minor, v2.0

#667 Adsk Contrib - Move non SSE build from windows to linux
  .appveyor.yml
  .travis.yml
Labels: Minor, v2.0

#666 Adsk Contrib - Rename LUT inversion quality member to clarify the use of the member.
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/OpTools.cpp
  src/OpenColorIO/OpTools.h
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpCPU.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.h
  src/OpenColorIO/ops/Lut3D/Lut3DOp.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpCPU.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpData.h
Labels: Minor, v2.0

#679 Update RB-1.1 CI builds to resolve failure cases
  .appveyor.yml
  .travis.yml
Labels: v1.0

#686 Adsk Contrib - Fix ocioconvert build break
  src/apps/ocioconvert/main.cpp
Labels: Major, v1.0, v2.0

#670 Adsk Contrib - Add a possibility to disable a GPU test at compile time.
  tests/gpu/GPUUnitTest.cpp
  tests/gpu/GPUUnitTest.h
  tests/gpu/Lut3DOp_test.cpp
Labels: Minor, v2.0
