Repository AcademySoftwareFoundation/OpenColorIO, pull requests merged in 2019-11, with the labels that each got.

#880 Fix AZP macOS dependency install failure
  share/ci/scripts/macos/install.sh
  share/ci/scripts/macos/install_python.sh
Labels: Critical

#875 Adsk Contrib - Fix the active views sorting and filtering behavior
  src/OpenColorIO/Config.cpp
Labels: Major, v2.0

#879 Adsk Contrib - Add baking support for CLF/CTF.
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/Baker.cpp
  src/OpenColorIO/Op.cpp
  src/OpenColorIO/fileformats/FileFormatCSP.cpp
  src/OpenColorIO/fileformats/FileFormatCTF.cpp
  src/OpenColorIO/fileformats/FileFormatIridasCube.cpp
  src/OpenColorIO/fileformats/FileFormatResolveCube.cpp
  src/OpenColorIO/fileformats/FormatMetadata.cpp
  src/OpenColorIO/fileformats/FormatMetadata.h
  src/OpenColorIO/fileformats/ctf/CTFReaderUtils.h
  src/OpenColorIO/fileformats/ctf/CTFTransform.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOp.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpData.cpp
  src/bindings/python/DocStrings/Baker.py
  src/bindings/python/PyBaker.cpp
  tests/cpu/fileformats/FileFormat3DL_tests.cpp
  tests/cpu/fileformats/FileFormatCTF_tests.cpp
  tests/cpu/transforms/FileTransform_tests.cpp
  tests/python/Baker.py
Labels: Minor, v2.0

#883 Adsk Contrib - Fix the display order issue
  ext/CMakeLists.txt
  share/cmake/modules/FindYamlCpp.cmake
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/Display.cpp
  src/OpenColorIO/Display.h
  src/OpenColorIO/OCIOYaml.cpp
Labels: Major, v2.0

#885 Adsk Contrib - Logging and misc. changes
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/ColorSpace.cpp
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/GpuShaderDesc.cpp
  src/OpenColorIO/Logging.cpp
  src/OpenColorIO/fileformats/FileFormatCC.cpp
  src/OpenColorIO/fileformats/FileFormatCDL.cpp
  src/OpenColorIO/ops/Lut1D/Lut1DOpGPU.cpp
  src/OpenColorIO/ops/Lut3D/Lut3DOpGPU.cpp
  src/utils/oglbuilder/glsl.h
  src/utils/oiiohelpers/oiiohelpers.h
  tests/cpu/CMakeLists.txt
  tests/cpu/Logging_tests.cpp
  tests/cpu/UnitTestLogUtils.cpp
  tests/cpu/UnitTestLogUtils.h
  tests/cpu/UnitTestUtils.cpp
  tests/cpu/UnitTestUtils.h
  tests/cpu/fileformats/FileFormatCTF_tests.cpp
  tests/gpu/Config_test.cpp
Labels: Minor, v2.0

#887 Adsk Contrib - Some Yaml cleanup
  share/cmake/modules/FindYamlCpp.cmake
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/OCIOYaml.h
Labels: Minor, v2.0

#888 Azure Build - Update the 'latest' build to use the latest Yaml.
  azure-pipelines.yml
  docs/installation.rst
Labels: Critical
