Repository AcademySoftwareFoundation/OpenColorIO, pull requests merged in 2020-08, with the labels that each got.

#1096 Adsk Contrib - Reorganize and add new documentation
  docs/_static/ocio_b.svg
  docs/api/_index.rst
  docs/concepts/_index.rst
  docs/concepts/overview/glossary.rst
  docs/concepts/overview/internal_architecture.rst
  docs/concepts/overview/introduction.rst
  docs/concepts/overview/overview.rst
  docs/concepts/publications/cinematic_color.rst
  docs/concepts/publications/publications.rst
  docs/conf.py
  docs/configurations/_images/gn10_to_linear_light.jpeg
  docs/configurations/_images/gnf_to_linear_light.jpeg
  docs/configurations/_images/lg10_to_linear_light.jpeg
  docs/configurations/_images/lg8_to_vd8.jpeg
  docs/configurations/_images/lgf_to_linear_light.jpeg
  docs/configurations/_index.rst
  docs/configurations/aces_1.0.3.rst
  docs/configurations/nuke_default.rst
  docs/configurations/spi_anim.rst
  docs/configurations/spi_vfx.rst
  docs/guides/_index.rst
  docs/guides/authoring/allocation_vars.rst
  docs/guides/authoring/authoring.rst
  docs/guides/authoring/colorspaces.rst
  docs/guides/authoring/contexts.rst
  docs/guides/authoring/displays_views.rst
  docs/guides/authoring/looks.rst
  docs/guides/authoring/looks_example.rst
  docs/guides/authoring/overview.rst
  docs/guides/authoring/rules.rst
  docs/guides/authoring/transforms.rst
  docs/guides/contributing/contributing.rst
  docs/guides/developing/app_helpers.rst
  docs/guides/developing/developing.rst
  docs/guides/developing/usage_examples.rst
  docs/guides/using_ocio/faq.rst
  docs/guides/using_ocio/tool_overview.rst
  docs/guides/using_ocio/using_ocio.rst
  docs/index.rst
  docs/quick_start/_index.rst
  docs/quick_start/about_docs.rst
  docs/quick_start/for_artists.rst
  docs/quick_start/installation.rst
  docs/toc_redirect.rst
  docs/tutorials/_index.rst
  docs/tutorials/baking_luts.rst
  docs/tutorials/contributing.rst
  docs/tutorials/tool_overview.rst
  docs/upgrading_v2/_index.rst
  docs/upgrading_v2/how_to.rst
Labels: Critical, Documentation, v2.0

#1098 Adsk Contrib - Temp quick start documentation and link fix
  docs/concepts/overview/glossary.rst
  docs/configurations/_index.rst
  docs/index.rst
  docs/quick_start/for_artists.rst
  docs/quick_start/for_config_authors.rst
  docs/quick_start/for_contributors.rst
  docs/quick_start/for_devs.rst
Labels: Documentation, v2.0

#1099 Adsk Contrib - Improve cmake build
  CMakeLists.txt
  share/cmake/modules/Findlcms2.cmake
  share/cmake/modules/Findpybind11.cmake
  share/cmake/modules/Findyaml-cpp.cmake
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/res/OpenColorIO.pc.in
  src/OpenColorIO/res/version.rc.in
Labels: v2.0

#1112 Adsk Contrib - Improve GLEW detection
  .github/workflows/ci_workflow.yml
  CMakeLists.txt
  src/apps/ociobakelut/main.cpp
Labels: v2.0
