Repository AcademySoftwareFoundation/OpenColorIO, pull requests merged in 2020-12, with the labels that each got.

#1205 Adsk Contrib - Remove dynamic properties from configs
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTransforms.h
  src/OpenColorIO/CPUProcessor.cpp
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/GPUProcessor.cpp
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/Op.cpp
  src/OpenColorIO/Op.h
  src/OpenColorIO/Processor.cpp
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOpCPU.cpp
  src/OpenColorIO/ops/exposurecontrast/ExposureContrastOpGPU.cpp
  src/OpenColorIO/ops/gradingprimary/GradingPrimaryOpCPU.cpp
  src/OpenColorIO/ops/gradingprimary/GradingPrimaryOpGPU.cpp
  src/OpenColorIO/ops/gradingrgbcurve/GradingRGBCurveOpCPU.cpp
  src/OpenColorIO/ops/gradingrgbcurve/GradingRGBCurveOpGPU.cpp
  src/OpenColorIO/ops/gradingtone/GradingToneOpCPU.cpp
  src/OpenColorIO/ops/gradingtone/GradingToneOpGPU.cpp
  tests/cpu/Config_tests.cpp
  tests/cpu/Processor_tests.cpp
  tests/cpu/fileformats/FileFormatCTF_tests.cpp
  tests/cpu/ops/exposurecontrast/ExposureContrastOpCPU_tests.cpp
  tests/cpu/ops/gradingprimary/GradingPrimaryOpCPU_tests.cpp
  tests/cpu/transforms/ExposureContrastTransform_tests.cpp
  tests/cpu/transforms/GradingPrimaryTransform_tests.cpp
  tests/cpu/transforms/GradingRGBCurveTransform_tests.cpp
  tests/data/files/exposure_contrast_log.ctf
  tests/gpu/ECOp_test.cpp
Labels: v2.0

#1204 Adsk Contrib - Some API cleanup
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTransforms.h
  src/OpenColorIO/transforms/FileTransform.cpp
  src/apps/ociochecklut/main.cpp
  src/bindings/python/PyFileTransform.cpp
Labels: v2.0

#1228 Fix build break: Bump pybind11 required version to 2.6.1
  share/cmake/modules/FindExtPackages.cmake
Labels: Critical

#1208 Adsk Contrib - Remove the 'unknown' shader language
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/GpuShaderDesc.cpp
  src/OpenColorIO/GpuShaderUtils.cpp
  src/OpenColorIO/ParseUtils.cpp
  src/bindings/python/PyTypes.cpp
  tests/cpu/ParseUtils_tests.cpp
Labels: v2.0

#1189 Adsk Contrib - Named color transforms
  include/OpenColorIO/OpenColorIO.h
  include/OpenColorIO/OpenColorTypes.h
  src/OpenColorIO/CMakeLists.txt
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/FileRules.cpp
  src/OpenColorIO/FileRules.h
  src/OpenColorIO/NamedTransform.cpp
  src/OpenColorIO/NamedTransform.h
  src/OpenColorIO/OCIOYaml.cpp
  src/OpenColorIO/TokensManager.h
  src/OpenColorIO/transforms/ColorSpaceTransform.cpp
  src/OpenColorIO/transforms/DisplayViewTransform.cpp
  src/bindings/python/CMakeLists.txt
  src/bindings/python/PyConfig.cpp
  src/bindings/python/PyNamedTransform.cpp
  src/bindings/python/PyOpenColorIO.cpp
  src/bindings/python/PyOpenColorIO.h
  src/bindings/python/PyTransform.h
  src/bindings/python/PyTypes.cpp
  src/libutils/apphelpers/CategoryHelpers.cpp
  src/libutils/apphelpers/CategoryHelpers.h
  src/libutils/apphelpers/ColorSpaceHelpers.cpp
  src/libutils/apphelpers/ColorSpaceHelpers.h
  src/libutils/apphelpers/DisplayViewHelpers.cpp
  tests/apphelpers/CategoryHelpers_tests.cpp
  tests/apphelpers/ColorSpaceHelpers_tests.cpp
  tests/apphelpers/DisplayViewHelpers_tests.cpp
  tests/apphelpers/configs.data
  tests/cpu/CMakeLists.txt
  tests/cpu/Config_tests.cpp
  tests/cpu/Display_tests.cpp
  tests/cpu/FileRules_tests.cpp
  tests/cpu/NamedTransform_tests.cpp
  tests/cpu/transforms/ColorSpaceTransform_tests.cpp
  tests/cpu/transforms/DisplayViewTransform_tests.cpp
  tests/python/ConfigTest.py
  tests/python/DisplayViewTransformTest.py
  tests/python/NamedTransformTest.py
  tests/python/OpenColorIOTestSuite.py
Labels: Critical, tsc-review, v2.0

#1229 Adsk Contrib - Data bypass fix
  CMakeLists.txt
  src/OpenColorIO/Config.cpp
  src/OpenColorIO/Processor.cpp
  src/OpenColorIO/transforms/LookTransform.cpp
  src/apps/ociochecklut/main.cpp
  tests/cpu/FileRules_tests.cpp
  tests/cpu/transforms/ColorSpaceTransform_tests.cpp
  tests/cpu/transforms/LookTransform_tests.cpp
Labels: Critical, v2.0

#1214 Adsk Contrib - Various file rule improvements
  include/OpenColorIO/OpenColorIO.h
  src/OpenColorIO/FileRules.cpp
  src/OpenColorIO/FileRules.h
  src/OpenColorIO/OCIOYaml.cpp
  tests/cpu/FileRules_tests.cpp
Labels: v2.0
